import { FieldValue } from "firebase-admin/firestore";

import { PlatformError } from "../errors/platform-error";
import { auditEventsCollectionRef } from "../firestore/typed-ref";
import type {
  ActorRole,
  AuditAction,
  AuditEventWrite,
  AuditPayload,
  AuditTargetType,
} from "../types/audit-event";
import type { Role } from "../types/user";

// Input shape for the canonical audit writer.
//
// Every required field mirrors Data Model §3.8 exactly. `occurredAt` is
// omitted because it is generated by the server via
// `FieldValue.serverTimestamp()`; supplying it from the caller would create
// two sources of truth for event time and would be rejected by the
// evidentiary-value guarantee stated in Cloud Function Charter §2.
export type WriteAuditEventInput = {
  readonly actorUserId: string;
  readonly actorRole: ActorRole;
  readonly action: AuditAction;
  readonly targetType: AuditTargetType;
  readonly targetId: string;
  readonly schoolId?: string;
  readonly payload?: AuditPayload;
  readonly correlationId?: string;
};

// Return value of a successful audit write. `eventId` is the opaque
// Firestore document ID of the new event. `record` is the exact write
// payload sent to Firestore, minus the server-timestamp sentinel, so
// callers can log it deterministically.
export type WriteAuditEventResult = {
  readonly eventId: string;
  readonly record: Omit<AuditEventWrite, "occurredAt">;
};

const VALID_ROLES: readonly Role[] = [
  "teacher",
  "student",
  "platformAdministrator",
];

// Canonical actor roles accepted by the audit writer per Data Model §3.8.
// Adds the `system` sentinel used by triggers and other trusted-server
// contexts. The domain `Role` union is unchanged, so no user-record shape
// or custom-claims path can accidentally acquire the sentinel.
const VALID_ACTOR_ROLES: readonly ActorRole[] = [...VALID_ROLES, "system"];

const VALID_ACTIONS: readonly AuditAction[] = [
  "auth.userProvisioned",
  "auth.activationRejected",
  "students.activated",
  "teachers.verificationRequested",
  "teachers.verificationApproved",
  "teachers.verificationDenied",
  "schools.created",
  "classes.created",
  "classes.metadataUpdated",
  "classes.archived",
  "classes.joinCodeRotated",
  "enrollments.created",
  "enrollments.statusChanged",
  "assignments.created",
  "assignments.updated",
  "assignments.published",
  "assignments.closed",
  "assignments.archived",
];

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function isValidActorRole(value: unknown): value is ActorRole {
  return (
    typeof value === "string" &&
    (VALID_ACTOR_ROLES as readonly string[]).includes(value)
  );
}

function isValidAction(value: unknown): value is AuditAction {
  return (
    typeof value === "string" &&
    (VALID_ACTIONS as readonly string[]).includes(value)
  );
}

// The single canonical path for writing audit events in the platform.
//
// Every callable, trigger, and administrative script that must record a
// security-relevant event routes through this helper. No second write path
// exists. The helper enforces:
//
// - the canonical shape invariant: the object written to Firestore
//   contains exactly the Data Model §3.8 fields (required, plus any
//   supplied optional payload and correlationId). No additional fields
//   are attached, and unknown fields on the input are ignored.
// - the canonical vocabulary invariant: `action` is a value from
//   the Sprint 2 audit vocabulary in Sprint 2 §4.5.
// - the server-time invariant: `occurredAt` is always
//   `FieldValue.serverTimestamp()`. Callers cannot backdate an event.
// - input validation: every required string is non-empty, `actorRole`
//   is a canonical `Role`, and `action` is a canonical `AuditAction`.
//
// Downstream Firestore failures are wrapped as `audit.writeFailed` with
// the original cause preserved.
export async function writeAuditEvent(
  input: WriteAuditEventInput,
): Promise<WriteAuditEventResult> {
  if (!isNonEmptyString(input.actorUserId)) {
    throw new PlatformError(
      "audit.invalidActorUserId",
      "actorUserId must be a non-empty string.",
    );
  }
  if (!isValidActorRole(input.actorRole)) {
    throw new PlatformError(
      "audit.invalidActorRole",
      `actorRole must be one of: ${VALID_ACTOR_ROLES.join(", ")}.`,
    );
  }
  if (!isValidAction(input.action)) {
    throw new PlatformError(
      "audit.invalidAction",
      `action must be a canonical audit vocabulary value (received "${String(input.action)}").`,
    );
  }
  if (!isNonEmptyString(input.targetType)) {
    throw new PlatformError(
      "audit.invalidTargetType",
      "targetType must be a non-empty string.",
    );
  }
  if (!isNonEmptyString(input.targetId)) {
    throw new PlatformError(
      "audit.invalidTargetId",
      "targetId must be a non-empty string.",
    );
  }
  // schoolId is conditionally required per Data Model §3.8:
  //   - User-actor events must carry a non-empty schoolId.
  //   - System-actor events may omit schoolId when no school association
  //     exists at write time (e.g. `auth.userProvisioned`). If the caller
  //     does supply a schoolId for a system-actor event, it must still be
  //     a non-empty string; empty-string is never a permitted value.
  if (input.actorRole === "system") {
    if (input.schoolId !== undefined && !isNonEmptyString(input.schoolId)) {
      throw new PlatformError(
        "audit.invalidSchoolId",
        "schoolId, when supplied, must be a non-empty string.",
      );
    }
  } else if (!isNonEmptyString(input.schoolId)) {
    throw new PlatformError(
      "audit.invalidSchoolId",
      "schoolId must be a non-empty string for user-actor events.",
    );
  }
  if (input.correlationId !== undefined && !isNonEmptyString(input.correlationId)) {
    throw new PlatformError(
      "audit.invalidCorrelationId",
      "correlationId, when supplied, must be a non-empty string.",
    );
  }
  if (
    input.payload !== undefined &&
    (input.payload === null || typeof input.payload !== "object" || Array.isArray(input.payload))
  ) {
    throw new PlatformError(
      "audit.invalidPayload",
      "payload, when supplied, must be a structured object.",
    );
  }

  const canonical: Omit<AuditEventWrite, "occurredAt"> = {
    actorUserId: input.actorUserId,
    actorRole: input.actorRole,
    action: input.action,
    targetType: input.targetType,
    targetId: input.targetId,
    ...(input.schoolId !== undefined ? { schoolId: input.schoolId } : {}),
    ...(input.payload !== undefined ? { payload: input.payload } : {}),
    ...(input.correlationId !== undefined
      ? { correlationId: input.correlationId }
      : {}),
  };

  const write: AuditEventWrite = {
    ...canonical,
    occurredAt: FieldValue.serverTimestamp(),
  };

  try {
    const ref = await auditEventsCollectionRef().add(write);
    return { eventId: ref.id, record: canonical };
  } catch (err) {
    throw new PlatformError(
      "audit.writeFailed",
      "Failed to write audit event.",
      err,
    );
  }
}
