import {
  FieldValue,
  type DocumentReference,
  type Transaction,
} from "firebase-admin/firestore";

import { PlatformError } from "../errors/platform-error";
import { auditEventsCollectionRef } from "../firestore/typed-ref";
import {
  AUDIT_ACTIONS,
  type ActorRole,
  type AuditAction,
  type AuditEventWrite,
  type AuditPayload,
  type AuditTargetType,
} from "../types/audit-event";
import type { Role } from "../types/user";

// Input shape for the canonical audit writer.
//
// Every required field mirrors Data Model §3.8 exactly. `occurredAt` is
// omitted because it is generated by the server via
// `FieldValue.serverTimestamp()`; supplying it from the caller would create
// two sources of truth for event time and would be rejected by the
// evidentiary-value guarantee stated in Cloud Function Charter §2.
export type WriteAuditEventInput = {
  readonly actorUserId: string;
  readonly actorRole: ActorRole;
  readonly action: AuditAction;
  readonly targetType: AuditTargetType;
  readonly targetId: string;
  readonly schoolId?: string;
  // Sprint 11D I-5. District context per DISTRICT_SECURITY_BOUNDARY_
  // IMPLEMENTATION_CONTRACT.md §7 auditEvents row: every district-relevant
  // event MUST carry a top-level `districtId` field. Optional at the type
  // level so pre-district system events (e.g. `auth.userProvisioned`) can
  // still be written. When supplied it MUST be a non-empty string.
  readonly districtId?: string;
  readonly payload?: AuditPayload;
  readonly correlationId?: string;
};

// Return value of a successful audit write. `eventId` is the opaque
// Firestore document ID of the new event. `record` is the exact write
// payload sent to Firestore, minus the server-timestamp sentinel, so
// callers can log it deterministically.
export type WriteAuditEventResult = {
  readonly eventId: string;
  readonly record: Omit<AuditEventWrite, "occurredAt">;
};

const VALID_ROLES: readonly Role[] = [
  "teacher",
  "student",
  "platformAdministrator",
];

// Canonical actor roles accepted by the audit writer per Data Model §3.8.
// Adds the `system` sentinel used by triggers and other trusted-server
// contexts. The domain `Role` union is unchanged, so no user-record shape
// or custom-claims path can accidentally acquire the sentinel.
const VALID_ACTOR_ROLES: readonly ActorRole[] = [...VALID_ROLES, "system"];

// Runtime allowlist for `action`. Sourced directly from the single canonical
// tuple in `../types/audit-event.ts` so the runtime validator and the
// `AuditAction` type can never drift. Adding a new action anywhere requires
// adding it to `AUDIT_ACTIONS`; both the type system and the runtime check
// pick it up in the same commit.

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function isValidActorRole(value: unknown): value is ActorRole {
  return (
    typeof value === "string" &&
    (VALID_ACTOR_ROLES as readonly string[]).includes(value)
  );
}

function isValidAction(value: unknown): value is AuditAction {
  return (
    typeof value === "string" &&
    (AUDIT_ACTIONS as readonly string[]).includes(value)
  );
}

// The single canonical path for writing audit events in the platform.
//
// Every callable, trigger, and administrative script that must record a
// security-relevant event routes through this helper. No second write path
// exists. The helper enforces:
//
// - the canonical shape invariant: the object written to Firestore
//   contains exactly the Data Model §3.8 fields (required, plus any
//   supplied optional payload and correlationId). No additional fields
//   are attached, and unknown fields on the input are ignored.
// - the canonical vocabulary invariant: `action` is a value from
//   the Sprint 2 audit vocabulary in Sprint 2 §4.5.
// - the server-time invariant: `occurredAt` is always
//   `FieldValue.serverTimestamp()`. Callers cannot backdate an event.
// - input validation: every required string is non-empty, `actorRole`
//   is a canonical `Role`, and `action` is a canonical `AuditAction`.
//
// Downstream Firestore failures are wrapped as `audit.writeFailed` with
// the original cause preserved.
//
// The validation and canonical-shape construction are factored into
// `buildAuditEventWrite` so there is still exactly ONE place that decides
// what a valid audit event looks like. Both the fire-and-forget
// `writeAuditEvent` (its own `.add()`) and the transaction-aware
// `writeAuditEventInTransaction` (a caller-provided `tx.set()`) consume
// that single builder, so a transaction-scoped audit write can never drift
// from the canonical shape or vocabulary the standalone writer enforces.
export type BuiltAuditEvent = {
  readonly write: AuditEventWrite;
  readonly record: Omit<AuditEventWrite, "occurredAt">;
};

// Validate the input and construct the canonical write. This performs no I/O
// and allocates no document reference, so it is safe to call inside a
// Firestore transaction body (the transaction writer allocates the ref
// itself via `.doc()`).
export function buildAuditEventWrite(
  input: WriteAuditEventInput,
): BuiltAuditEvent {
  if (!isNonEmptyString(input.actorUserId)) {
    throw new PlatformError(
      "audit.invalidActorUserId",
      "actorUserId must be a non-empty string.",
    );
  }
  if (!isValidActorRole(input.actorRole)) {
    throw new PlatformError(
      "audit.invalidActorRole",
      `actorRole must be one of: ${VALID_ACTOR_ROLES.join(", ")}.`,
    );
  }
  if (!isValidAction(input.action)) {
    throw new PlatformError(
      "audit.invalidAction",
      `action must be a canonical audit vocabulary value (received "${String(input.action)}").`,
    );
  }
  if (!isNonEmptyString(input.targetType)) {
    throw new PlatformError(
      "audit.invalidTargetType",
      "targetType must be a non-empty string.",
    );
  }
  if (!isNonEmptyString(input.targetId)) {
    throw new PlatformError(
      "audit.invalidTargetId",
      "targetId must be a non-empty string.",
    );
  }
  // schoolId is conditionally required per Data Model §3.8:
  //   - User-actor events must carry a non-empty schoolId.
  //   - System-actor events may omit schoolId when no school association
  //     exists at write time (e.g. `auth.userProvisioned`). If the caller
  //     does supply a schoolId for a system-actor event, it must still be
  //     a non-empty string; empty-string is never a permitted value.
  if (input.actorRole === "system") {
    if (input.schoolId !== undefined && !isNonEmptyString(input.schoolId)) {
      throw new PlatformError(
        "audit.invalidSchoolId",
        "schoolId, when supplied, must be a non-empty string.",
      );
    }
  } else if (!isNonEmptyString(input.schoolId)) {
    throw new PlatformError(
      "audit.invalidSchoolId",
      "schoolId must be a non-empty string for user-actor events.",
    );
  }
  if (input.districtId !== undefined && !isNonEmptyString(input.districtId)) {
    throw new PlatformError(
      "audit.invalidDistrictId",
      "districtId, when supplied, must be a non-empty string.",
    );
  }
  if (input.correlationId !== undefined && !isNonEmptyString(input.correlationId)) {
    throw new PlatformError(
      "audit.invalidCorrelationId",
      "correlationId, when supplied, must be a non-empty string.",
    );
  }
  if (
    input.payload !== undefined &&
    (input.payload === null || typeof input.payload !== "object" || Array.isArray(input.payload))
  ) {
    throw new PlatformError(
      "audit.invalidPayload",
      "payload, when supplied, must be a structured object.",
    );
  }

  const canonical: Omit<AuditEventWrite, "occurredAt"> = {
    actorUserId: input.actorUserId,
    actorRole: input.actorRole,
    action: input.action,
    targetType: input.targetType,
    targetId: input.targetId,
    ...(input.schoolId !== undefined ? { schoolId: input.schoolId } : {}),
    ...(input.districtId !== undefined ? { districtId: input.districtId } : {}),
    ...(input.payload !== undefined ? { payload: input.payload } : {}),
    ...(input.correlationId !== undefined
      ? { correlationId: input.correlationId }
      : {}),
  };

  const write: AuditEventWrite = {
    ...canonical,
    occurredAt: FieldValue.serverTimestamp(),
  };

  return { write, record: canonical };
}

export async function writeAuditEvent(
  input: WriteAuditEventInput,
): Promise<WriteAuditEventResult> {
  const { write, record } = buildAuditEventWrite(input);
  try {
    const ref = await auditEventsCollectionRef().add(write);
    return { eventId: ref.id, record };
  } catch (err) {
    throw new PlatformError(
      "audit.writeFailed",
      "Failed to write audit event.",
      err,
    );
  }
}

// Transaction-aware audit writer. Enlists the canonical audit event into a
// caller-provided Firestore transaction via `tx.set`, so the audit event
// commits atomically with the state transition that produced it and cannot
// exist without that transition (or the transition without it). Firestore
// requires all reads in a transaction to precede all writes, so the caller
// must have completed its transactional reads before calling this. The
// returned `eventId` is the id the event will carry once the transaction
// commits; if the transaction aborts, no event is written. Input validation
// throws synchronously (aborting the enclosing transaction) exactly as the
// standalone writer does.
export function writeAuditEventInTransaction(
  tx: Transaction,
  input: WriteAuditEventInput,
): WriteAuditEventResult {
  const { write, record } = buildAuditEventWrite(input);
  const ref: DocumentReference<AuditEventWrite> = auditEventsCollectionRef().doc();
  tx.set(ref, write);
  return { eventId: ref.id, record };
}
