export {
  writeAuditEvent,
  type WriteAuditEventInput,
  type WriteAuditEventResult,
} from "./audit/write-audit-event";
export {
  writeCustomClaims,
  type CanonicalCustomClaims,
  type WriteCustomClaimsInput,
} from "./auth/claims";
export {
  requireDistrictContext,
  type DistrictClaimToken,
  type DistrictContext,
} from "./auth/require-district-context";
export {
  DISTRICT_ERROR_IDS,
  isDistrictErrorId,
  type DistrictErrorId,
} from "./errors/district-errors";
export { PlatformError } from "./errors/platform-error";
export {
  assessmentSessionAutosaveDocRef,
  assessmentSessionCreationDocRef,
  assessmentSessionDocRef,
  assessmentSessionsCollectionRef,
  assignmentArchiveDocRef,
  assignmentCloseDocRef,
  assignmentCreationDocRef,
  assignmentDocRef,
  assignmentDraftUpdateDocRef,
  assignmentLmsPublicationDocRef,
  assignmentPublishDocRef,
  assignmentsCollectionRef,
  auditEventsCollectionRef,
  classArchiveDocRef,
  classCreationDocRef,
  classDocRef,
  classLmsLinkDocRef,
  classMetadataUpdateDocRef,
  classesCollectionRef,
  lmsAssignmentPublicationCreationDocRef,
  lmsAssignmentPublicationDocRef,
  lmsAssignmentPublicationsCollectionRef,
  lmsClassLinkBreakDocRef,
  lmsClassLinkCreationDocRef,
  lmsClassLinkDocRef,
  lmsClassLinkUnlinkDocRef,
  lmsClassLinksCollectionRef,
  lmsConnectionCreationDocRef,
  lmsConnectionDocRef,
  lmsConnectionRevocationDocRef,
  lmsConnectionsCollectionRef,
  lmsProviderCreationDocRef,
  lmsProviderDocRef,
  lmsProvidersCollectionRef,
  enrollmentCreationDocRef,
  enrollmentDocRef,
  enrollmentStatusChangeDocRef,
  enrollmentsCollectionRef,
  schoolCreationDocRef,
  schoolDocRef,
  submissionCreationDocRef,
  submissionDocRef,
  submissionFinalizationDocRef,
  submissionsCollectionRef,
  userDocRef,
  userRecordDocRef,
} from "./firestore/typed-ref";
export { log, type LogPayload } from "./logging/logger";
export {
  ASSIGNMENTS_COLLECTION,
  type AssignmentArchiveWrite,
  type AssignmentCloseWrite,
  type AssignmentCreationWrite,
  type AssignmentDraftUpdateWrite,
  type AssignmentLmsPublicationWrite,
  type AssignmentMode,
  type AssignmentPublishWrite,
  type AssignmentRecord,
  type AssignmentStatus,
} from "./types/assignment";
export {
  AUDIT_EVENTS_COLLECTION,
  type ActorRole,
  type AuditAction,
  type AuditEventRecord,
  type AuditEventWrite,
  type AuditPayload,
  type AuditTargetType,
} from "./types/audit-event";
export {
  CLASSES_COLLECTION,
  type ClassArchiveWrite,
  type ClassCreationWrite,
  type ClassLmsLinkWrite,
  type ClassMetadataUpdateWrite,
  type ClassRecord,
  type ClassStatus,
} from "./types/class";
export {
  LMS_ASSIGNMENT_PUBLICATIONS_COLLECTION,
  LMS_CLASS_LINKS_COLLECTION,
  LMS_CONNECTIONS_COLLECTION,
  LMS_PROVIDERS_COLLECTION,
  type ClassEnrollmentSource,
  type LmsAssignmentPublicationCreationWrite,
  type LmsAssignmentPublicationRecord,
  type LmsAssignmentPublicationStatus,
  type LmsClassLinkBreakWrite,
  type LmsClassLinkCreationWrite,
  type LmsClassLinkRecord,
  type LmsClassLinkStatus,
  type LmsClassLinkUnlinkWrite,
  type LmsConnectionCreationWrite,
  type LmsConnectionRecord,
  type LmsConnectionRevocationWrite,
  type LmsConnectionStatus,
  type LmsProviderCreationWrite,
  type LmsProviderId,
  type LmsProviderRecord,
} from "./types/lms";
export {
  ENROLLMENTS_COLLECTION,
  type EnrollmentCreationWrite,
  type EnrollmentRecord,
  type EnrollmentStatus,
  type EnrollmentStatusChangeWrite,
} from "./types/enrollment";
export {
  SCHOOLS_COLLECTION,
  type SchoolCreationWrite,
  type SchoolRecord,
} from "./types/school";
export {
  SUBMISSIONS_COLLECTION,
  type SubmissionCreationWrite,
  type SubmissionFinalizationWrite,
  type SubmissionRecord,
  type SubmissionResponse,
  type SubmissionStatus,
} from "./types/submission";
export {
  ASSESSMENT_SESSIONS_COLLECTION,
  type AssessmentSessionAutosaveWrite,
  type AssessmentSessionCreationWrite,
  type AssessmentSessionRecord,
  type AssessmentSessionResponse,
  type AssessmentSessionStatus,
} from "./types/assessment-session";
export {
  USERS_COLLECTION,
  type ConsentState,
  type Role,
  type StudentActivationWrite,
  type StudentProfile,
  type TeacherApprovalWrite,
  type TeacherDenialWrite,
  type TeacherProfile,
  type TeacherVerificationRequestWrite,
  type UserProvisioningWrite,
  type UserRecord,
  type UserStatus,
} from "./types/user";
