export {
  buildAuditEventWrite,
  writeAuditEvent,
  writeAuditEventInTransaction,
  type BuiltAuditEvent,
  type WriteAuditEventInput,
  type WriteAuditEventResult,
} from "./audit/write-audit-event";
export {
  clearCustomClaims,
  readCustomClaims,
  writeCustomClaims,
  type CanonicalCustomClaims,
  type CustomClaimsView,
  type WriteCustomClaimsInput,
} from "./auth/claims";
export { revokeUserRefreshTokens } from "./auth/refresh-tokens";
export {
  PLATFORM_CONFIG_COLLECTION,
  TEACHER_PILOT_ALLOWLIST_DOC_ID,
  assertTeacherPilotAllowlisted,
  assertTeacherPilotAllowlistedInTransaction,
  isTeacherPilotAllowlisted,
  teacherPilotAllowlistDocRef,
  normalizeEmail,
  resolvePilotSchoolId,
  type TeacherPilotAllowlistDoc,
} from "./config/teacher-pilot-allowlist";
export {
  DIFFERENTIATED_DELIVERY_CONFIG_DOC_ID,
  isDifferentiatedDeliveryEnabled,
  type DifferentiatedDeliveryConfigDoc,
} from "./config/differentiated-delivery-flag";
export {
  requireDistrictContext,
  type DistrictClaimToken,
  type DistrictContext,
} from "./auth/require-district-context";
export {
  requireActivePlatformAdministrator,
  assertActivePlatformAdministratorInTransaction,
  type ActivePlatformAdministratorContext,
  type RequireActivePlatformAdministratorOptions,
} from "./auth/require-active-platform-administrator";
export {
  DISTRICT_ERROR_IDS,
  isDistrictErrorId,
  type DistrictErrorId,
} from "./errors/district-errors";
export { PlatformError } from "./errors/platform-error";
export {
  READING_LEVELS,
  STUDENT_ACCOMMODATIONS_COLLECTION,
  ACCOMMODATION_HISTORY_SUBCOLLECTION,
  accommodationHistoryDocId,
  type AccommodationHistoryRecord,
  type AccommodationHistoryWrite,
  type ReadingAccessibilityConfig,
  type ReadingLevel,
  type StudentAccommodationCreationWrite,
  type StudentAccommodationRecord,
  type StudentAccommodationUpdateWrite,
} from "./types/student-accommodation";
export {
  ACTIVE_LAB_REPORT_ID,
  LAB_REPORT_FORMAT_VERSION,
  STUDENT_LAB_REPORTS_COLLECTION,
  STUDENT_LAB_REPORT_ITEMS_SUBCOLLECTION,
  STUDENT_LAB_REPORT_SCHEMA_VERSION,
  type StudentLabReportCreationWrite,
  type StudentLabReportRecord,
  type StudentLabReportScope,
  type StudentLabReportUpdateWrite,
} from "./types/student-lab-report";
export {
  assessmentIdForLessonSlug,
  revisionIdForOrdinal,
  parseAssessmentIdFromRevisionId,
  parseRevisionOrdinalFromRevisionId,
  resolveCurrentAssessmentRevisionId,
} from "./assessment-identifiers";
export {
  ASSIGNMENT_RESOURCE_TYPES,
  DEFAULT_ASSIGNMENT_RESOURCE_TYPE,
  RESERVED_ACTIVITY_ID_PREFIXES,
  assertActivityIdMatchesResourceType,
  assertAssignableActivity,
  isAssignmentResourceType,
  isResourceTypeAssignable,
  parseAssignmentResourceType,
  reservedResourceTypeForActivityId,
} from "./activity-identifiers";
export {
  mapPlatformCodeToHttpsCode,
  platformCallable,
  translateThrown,
} from "./errors/https-callable";
export {
  LEGACY_SUBMISSIONS_ENV_VAR,
  assertLegacySubmissionsWritesEnabled,
  legacySubmissionsWritesEnabled,
} from "./legacy-submissions-flag";
export {
  assessmentAnswerKeyDeploymentDocRef,
  assessmentAnswerKeyDocRef,
  assessmentDeploymentDocRef,
  assessmentDocRef,
  completionDefinitionCreationDocRef,
  completionDefinitionDocRef,
  assessmentRevisionDeploymentDocRef,
  assessmentRevisionDocRef,
  assessmentSessionAutosaveDocRef,
  assessmentSessionCreationDocRef,
  assessmentSessionDocRef,
  assessmentSessionsCollectionRef,
  attemptCreationDocRef,
  attemptDocRef,
  attemptsCollectionRef,
  assignmentArchiveDocRef,
  assignmentCreationDocRef,
  assignmentDocRef,
  assignmentDraftUpdateDocRef,
  assignmentLmsPublicationDocRef,
  assignmentPublishDocRef,
  assignmentReopenDocRef,
  assignmentRecipientCreationDocRef,
  assignmentRecipientDocRef,
  assignmentRecipientsCollectionGroupRef,
  assignmentRecipientsCollectionRef,
  assignmentsCollectionRef,
  auditEventsCollectionRef,
  classActivationDocRef,
  classArchiveDocRef,
  classCreationDocRef,
  classDocRef,
  classLmsCreationDocRef,
  classLmsLinkDocRef,
  classMetadataUpdateDocRef,
  classesCollectionRef,
  lmsAssignmentPublicationCreationDocRef,
  lmsAssignmentPublicationDocRef,
  lmsAssignmentPublicationsCollectionRef,
  lmsClassLinkBreakDocRef,
  lmsClassLinkCreationDocRef,
  lmsClassLinkDocRef,
  lmsClassLinkUnlinkDocRef,
  lmsClassLinksCollectionRef,
  lmsConnectionCreationDocRef,
  lmsConnectionDocRef,
  lmsConnectionRevocationDocRef,
  lmsConnectionsCollectionRef,
  lmsProviderCreationDocRef,
  lmsProviderDocRef,
  lmsProvidersCollectionRef,
  lmsRosterMembershipsCollectionRef,
  lmsRosterMembershipDocRef,
  lmsRosterMembershipCreationDocRef,
  lmsRosterMembershipReaffirmDocRef,
  lmsRosterMembershipRemovalDocRef,
  enrollmentCreationDocRef,
  enrollmentDocRef,
  enrollmentStatusChangeDocRef,
  enrollmentClassroomWithdrawalDocRef,
  enrollmentClassroomReactivationDocRef,
  enrollmentsCollectionRef,
  schoolCreationDocRef,
  schoolDocRef,
  submissionCreationDocRef,
  submissionDocRef,
  submissionFinalizationDocRef,
  submissionsCollectionRef,
  teacherPreferencesDocRef,
  teacherPreferencesUpdateDocRef,
  userDocRef,
  userRecordDocRef,
  externalIdentitiesCollectionRef,
  externalIdentityDocRef,
  externalIdentityCreationDocRef,
  externalIdentityRevocationDocRef,
  externalIdentityRestorationDocRef,
  studentAccommodationDocRef,
  studentAccommodationCreationDocRef,
  studentAccommodationUpdateDocRef,
  studentAccommodationHistoryDocRef,
  studentLabReportDocRef,
  studentLabReportCreationDocRef,
  studentLabReportUpdateDocRef,
} from "./firestore/typed-ref";
export {
  teacherUnitCreateReceiptCreationDocRef,
  teacherUnitCreateReceiptDocRef,
  teacherUnitCreationDocRef,
  teacherUnitDocRef,
  teacherUnitUpdateDocRef,
  teacherUnitsCollectionRef,
} from "./firestore/typed-ref";
export {
  TEACHER_UNITS_COLLECTION,
  TEACHER_UNIT_CREATE_RECEIPTS_COLLECTION,
  TEACHER_UNIT_CREATE_RECEIPT_RETENTION_MS,
  TEACHER_UNIT_DEFAULT_SORT_ORDER,
  TEACHER_UNIT_DESCRIPTION_MAX_LENGTH,
  TEACHER_UNIT_FIRST_ORDERED_POSITION,
  TEACHER_UNIT_GRADES,
  TEACHER_UNIT_INITIAL_REVISION,
  TEACHER_UNIT_RESOURCES_MAX,
  TEACHER_UNIT_STATUSES,
  TEACHER_UNIT_TITLE_MAX_LENGTH,
  TEACHER_UNITS_REORDER_MAX,
  isTeacherUnitGrade,
  type TeacherUnitCreateReceiptRecord,
  type TeacherUnitCreateReceiptWrite,
  type TeacherUnitCreationWrite,
  type TeacherUnitGrade,
  type TeacherUnitRecord,
  type TeacherUnitStatus,
  type TeacherUnitUpdateWrite,
} from "./types/teacher-unit";
export {
  launchGrantCreationDocRef,
  launchGrantDocRef,
  assessmentPresentationDocRef,
} from "./firestore/typed-ref";
export {
  presentationVariantIndexDocRef,
  presentationVariantScopedIndexDocRef,
} from "./firestore/typed-ref";
export {
  PRESENTATION_VARIANTS_COLLECTION,
  presentationVariantIndexDocId,
  presentationVariantScopedIndexDocId,
  isValidPresentationRevisionId,
  isValidVariantKey,
  isValidLessonSlugForVariant,
  variantKeyForReadingLevel,
  assertActivateWriteConsistent,
  type PresentationVariantIndexDoc,
  type PresentationVariantStatus,
} from "./types/presentation-variant";
export {
  LAUNCH_GRANTS_COLLECTION,
  LAUNCH_GRANT_TTL_MS,
  assertLaunchGrantPairInvariant,
  computeGrantExpiryMs,
  isValidGrantId,
  type LaunchGrantCreationWrite,
  type LaunchGrantOutcomeAtIssuance,
  type LaunchGrantRecord,
} from "./types/launch-grant";
export { generateGrantId } from "./presentation/launch-grant-id";
export {
  createLaunchPresentationResolver,
  type LaunchFallbackReason,
  type LaunchPresentation,
  type LaunchPresentationResolution,
  type LaunchPresentationResolver,
  type LaunchPresentationResolverPorts,
  type LaunchPresentationTelemetryEvent,
  type MintGrantInput,
  type ReadingResolution,
  type ResolveLaunchPresentationInput,
  type VariantIndexEvaluation,
} from "./presentation/resolve-launch-presentation";
export {
  buildLaunchPresentationResolverPorts,
  createRequestLaunchPresentationResolver,
} from "./presentation/launch-presentation-deps";
export { isTransactionContention, runFirestoreTransaction } from "./firestore/transaction";
export { createFirestoreBatch } from "./firestore/batch";
export { log, type LogPayload } from "./logging/logger";
export { roundHalfToEven2 } from "./math/round-half-to-even";
export {
  ASSIGNMENTS_COLLECTION,
  type AssignmentArchiveWrite,
  type AssignmentCreationWrite,
  type AssignmentDraftUpdateWrite,
  type AssignmentLmsPublicationWrite,
  type AssignmentMode,
  type AssignmentResourceType,
  type AssignmentPublishWrite,
  type AssignmentReopenWrite,
  type AssignmentRecord,
  type AssignmentStatus,
  type ClassroomGradingConfig,
} from "./types/assignment";
export {
  ASSIGNMENT_COMPLETION_BINDING_SCHEMA_VERSION,
  COMPLETION_DEFINITIONS_COLLECTION,
  COMPLETION_DEFINITION_RECORD_SCHEMA_VERSION,
  type AssignmentCompletionBinding,
  type CompletionBindingResourceType,
  type CompletionDefinitionCreationWrite,
  type CompletionDefinitionRecord,
  type CompletionValidatorRef,
} from "./types/completion-definition";
export {
  ASSIGNMENT_RECIPIENTS_SUBCOLLECTION,
  type AssignmentRecipientCreationWrite,
  type AssignmentRecipientRecord,
  type AssignmentRecipientSource,
  type AssignmentRecipientStatus,
} from "./types/assignment-recipient";
export {
  ASSIGNMENTS_CURRENT_SUBCOLLECTION,
  type AssignmentCurrentRecord,
  type AssignmentCurrentSource,
  type AssignmentCurrentWrite,
} from "./types/assignment-current";
export {
  assignmentsCurrentDocRef,
  assignmentsCurrentSetDocRef,
} from "./firestore/typed-ref";
export {
  AUDIT_ACTIONS,
  AUDIT_EVENTS_COLLECTION,
  type ActorRole,
  type AuditAction,
  type AuditEventRecord,
  type AuditEventWrite,
  type AuditPayload,
  type AuditTargetType,
} from "./types/audit-event";
export {
  CLASSES_COLLECTION,
  type ActiveClassRecord,
  type ArchivedClassRecord,
  type ClassActivationWrite,
  type ClassArchiveWrite,
  type ClassCreationWrite,
  type ClassLmsCreationWrite,
  type ClassLmsLinkWrite,
  type ClassMetadataUpdateWrite,
  type ClassRecord,
  type ClassStatus,
  type NeedsSetupClassRecord,
} from "./types/class";
export {
  assertClassSupports,
  type ClassOperation,
} from "./classes";
export {
  LMS_ASSIGNMENT_PUBLICATIONS_COLLECTION,
  LMS_CLASS_LINKS_COLLECTION,
  LMS_CONNECTIONS_COLLECTION,
  LMS_PROVIDERS_COLLECTION,
  LMS_ROSTER_MEMBERSHIPS_COLLECTION,
  type ClassEnrollmentSource,
  type LmsAssignmentPublicationCreationWrite,
  type LmsAssignmentPublicationRecord,
  type LmsAssignmentPublicationStatus,
  type LmsPublicationInitialState,
  type LmsClassLinkBreakWrite,
  type LmsClassLinkCreationWrite,
  type LmsClassLinkRecord,
  type LmsClassLinkStatus,
  type LmsClassLinkUnlinkWrite,
  type LmsConnectionCreationWrite,
  type LmsConnectionRecord,
  type LmsConnectionRevocationWrite,
  type LmsConnectionStatus,
  type LmsProviderCreationWrite,
  type LmsProviderId,
  type LmsProviderRecord,
  type LmsRosterMembershipCreationWrite,
  type LmsRosterMembershipReaffirmWrite,
  type LmsRosterMembershipRecord,
  type LmsRosterMembershipRemovalWrite,
  type LmsRosterMembershipStatus,
} from "./types/lms";
export {
  LMS_GRADE_PASSBACKS_COLLECTION,
  type LmsGradePassbackRecord,
  type LmsGradePassbackStatus,
} from "./types/lms-grade-passback";
export {
  lmsGradePassbacksCollectionRef,
  lmsGradePassbackDocRef,
} from "./firestore/typed-ref";
export {
  ENROLLMENTS_COLLECTION,
  type ClassroomEnrollmentReactivationWrite,
  type ClassroomEnrollmentWithdrawalWrite,
  type EnrollmentCreationWrite,
  type EnrollmentExitSource,
  type EnrollmentRecord,
  type EnrollmentStatus,
  type EnrollmentStatusChangeWrite,
} from "./types/enrollment";
export {
  SCHOOLS_COLLECTION,
  type SchoolCreationWrite,
  type SchoolRecord,
} from "./types/school";
export {
  PLATFORM_ADMIN_BOOTSTRAP_COLLECTION,
  INITIAL_BOOTSTRAP_DOC_ID,
  PLATFORM_ADMIN_BOOTSTRAP_VERSION,
  isCanonicalTimestamp,
  type BootstrapLineageState,
  type PlatformAdminBootstrapRecord,
  type PlatformAdminBootstrapCreationWrite,
  type PlatformAdminBootstrapRollbackWrite,
} from "./types/platform-admin-bootstrap";
export {
  platformAdminBootstrapDocRef,
  platformAdminBootstrapCreationDocRef,
  platformAdminBootstrapRollbackDocRef,
} from "./firestore/typed-ref";
export {
  SUBMISSIONS_COLLECTION,
  type SubmissionCreationWrite,
  type SubmissionFinalizationWrite,
  type SubmissionRecord,
  type SubmissionResponse,
  type SubmissionStatus,
} from "./types/submission";
export {
  ASSESSMENT_SESSIONS_COLLECTION,
  type AssessmentSessionAutosaveWrite,
  type AssessmentSessionCreationWrite,
  type AssessmentSessionRecord,
  type AssessmentSessionResponse,
  type AssessmentSessionStatus,
  type DeliveryOutcome,
  type SessionDeliveryFreeze,
} from "./types/assessment-session";
export {
  ASSESSMENTS_COLLECTION,
  ASSESSMENT_ANSWER_KEYS_COLLECTION,
  ASSESSMENT_REVISIONS_COLLECTION,
  ASSESSMENT_SCHEMA_VERSION_V1,
  type AssessmentAnswerKeyDeploymentWrite,
  type AssessmentAnswerKeyItem,
  type AssessmentAnswerKeyRecord,
  type AssessmentDeploymentWrite,
  type AssessmentItemOrderingRule,
  type AssessmentItemType,
  type AssessmentRecord,
  type AssessmentRevisionDeploymentWrite,
  type AssessmentRevisionItem,
  type AssessmentRevisionItemOption,
  type AssessmentRevisionRecord,
  type AssessmentSchemaVersion,
} from "./types/assessment";
export {
  ATTEMPTS_COLLECTION,
  type AssessmentAttemptCreationWrite,
  type AssessmentAttemptItemResult,
  type AssessmentAttemptRecord,
} from "./types/attempt";
export {
  EXTERNAL_IDENTITIES_COLLECTION,
  type ExternalIdentityCreationWrite,
  type ExternalIdentityProviderId,
  type ExternalIdentityRecord,
  type ExternalIdentityRestorationWrite,
  type ExternalIdentityRevocationWrite,
  type ExternalIdentitySource,
  type ExternalIdentityStatus,
} from "./types/external-identity";
export {
  assertValidProviderAccountId,
  assertValidProviderId,
  computeExternalIdentityDocId,
  type ExternalIdentityDocIdInput,
} from "./identity/external-identity-doc-id";
export {
  createOrConfirmExternalIdentity,
  listActiveExternalIdentityHashesForUser,
  listExternalIdentitiesForUser,
  reconcileExternalIdentityForUser,
  resolveActiveExternalIdentity,
  resolveActiveUserIdByExternalIdentityDocId,
  resolveActiveProviderAccountIdForUser,
  restoreExternalIdentity,
  revokeExternalIdentity,
  type CreateOrConfirmInput,
  type CreateOrConfirmOutcome,
  type CreateOrConfirmResult,
  type ExternalIdentityResolution,
  type ReconcileForUserInput,
  type ReconcileForUserPerProviderResult,
  type ReconcileForUserResult,
  type RestoreInput,
  type RestoreOutcome,
  type RestoreResult,
  type RevokeInput,
  type RevokeOutcome,
  type RevokeResult,
} from "./identity/external-identity-store";
export {
  CLASS_COLOR_TOKENS,
  TEACHER_DEFAULT_GRADE_VALUES,
  TEACHER_PREFERENCES_DOC_ID,
  TEACHER_PREFERENCES_SUBCOLLECTION,
  isClassColorToken,
  isTeacherDefaultGrade,
  type ClassColorToken,
  type TeacherClassColorSetWrite,
  type TeacherClassOrderSetWrite,
  type TeacherDefaultGrade,
  type TeacherPreferencesClearWrite,
  type TeacherPreferencesDoc,
  type TeacherPreferencesSetWrite,
  type TeacherPreferencesUpdateWrite,
} from "./types/teacher-preferences";
export {
  USERS_COLLECTION,
  type ConsentState,
  type Role,
  type StudentActivationWrite,
  type StudentProfile,
  type TeacherApprovalWrite,
  type TeacherDenialWrite,
  type TeacherPilotActivationWrite,
  type TeacherProfile,
  type TeacherSuspensionWrite,
  type TeacherVerificationRequestWrite,
  type UserProvisioningWrite,
  type UserRecord,
  type UserStatus,
} from "./types/user";
