export {
  writeAuditEvent,
  type WriteAuditEventInput,
  type WriteAuditEventResult,
} from "./audit/write-audit-event";
export {
  readCustomClaims,
  writeCustomClaims,
  type CanonicalCustomClaims,
  type CustomClaimsView,
  type WriteCustomClaimsInput,
} from "./auth/claims";
export {
  PLATFORM_CONFIG_COLLECTION,
  TEACHER_PILOT_ALLOWLIST_DOC_ID,
  assertTeacherPilotAllowlisted,
  normalizeEmail,
  resolvePilotSchoolId,
  type TeacherPilotAllowlistDoc,
} from "./config/teacher-pilot-allowlist";
export {
  DIFFERENTIATED_DELIVERY_CONFIG_DOC_ID,
  isDifferentiatedDeliveryEnabled,
  type DifferentiatedDeliveryConfigDoc,
} from "./config/differentiated-delivery-flag";
export {
  requireDistrictContext,
  type DistrictClaimToken,
  type DistrictContext,
} from "./auth/require-district-context";
export {
  DISTRICT_ERROR_IDS,
  isDistrictErrorId,
  type DistrictErrorId,
} from "./errors/district-errors";
export { PlatformError } from "./errors/platform-error";
export {
  READING_LEVELS,
  STUDENT_ACCOMMODATIONS_COLLECTION,
  ACCOMMODATION_HISTORY_SUBCOLLECTION,
  accommodationHistoryDocId,
  type AccommodationHistoryRecord,
  type AccommodationHistoryWrite,
  type ReadingAccessibilityConfig,
  type ReadingLevel,
  type StudentAccommodationCreationWrite,
  type StudentAccommodationRecord,
  type StudentAccommodationUpdateWrite,
} from "./types/student-accommodation";
export {
  assessmentIdForLessonSlug,
  revisionIdForOrdinal,
  parseAssessmentIdFromRevisionId,
  parseRevisionOrdinalFromRevisionId,
  resolveCurrentAssessmentRevisionId,
} from "./assessment-identifiers";
export {
  mapPlatformCodeToHttpsCode,
  platformCallable,
  translateThrown,
} from "./errors/https-callable";
export {
  LEGACY_SUBMISSIONS_ENV_VAR,
  assertLegacySubmissionsWritesEnabled,
  legacySubmissionsWritesEnabled,
} from "./legacy-submissions-flag";
export {
  assessmentAnswerKeyDeploymentDocRef,
  assessmentAnswerKeyDocRef,
  assessmentDeploymentDocRef,
  assessmentDocRef,
  assessmentRevisionDeploymentDocRef,
  assessmentRevisionDocRef,
  assessmentSessionAutosaveDocRef,
  assessmentSessionCreationDocRef,
  assessmentSessionDocRef,
  assessmentSessionsCollectionRef,
  attemptCreationDocRef,
  attemptDocRef,
  attemptsCollectionRef,
  assignmentArchiveDocRef,
  assignmentCloseDocRef,
  assignmentCreationDocRef,
  assignmentDocRef,
  assignmentDraftUpdateDocRef,
  assignmentLmsPublicationDocRef,
  assignmentPublishDocRef,
  assignmentReopenDocRef,
  assignmentRecipientCreationDocRef,
  assignmentRecipientDocRef,
  assignmentRecipientsCollectionGroupRef,
  assignmentRecipientsCollectionRef,
  assignmentsCollectionRef,
  auditEventsCollectionRef,
  classActivationDocRef,
  classArchiveDocRef,
  classCreationDocRef,
  classDocRef,
  classLmsCreationDocRef,
  classLmsLinkDocRef,
  classMetadataUpdateDocRef,
  classesCollectionRef,
  lmsAssignmentPublicationCreationDocRef,
  lmsAssignmentPublicationDocRef,
  lmsAssignmentPublicationsCollectionRef,
  lmsClassLinkBreakDocRef,
  lmsClassLinkCreationDocRef,
  lmsClassLinkDocRef,
  lmsClassLinkUnlinkDocRef,
  lmsClassLinksCollectionRef,
  lmsConnectionCreationDocRef,
  lmsConnectionDocRef,
  lmsConnectionRevocationDocRef,
  lmsConnectionsCollectionRef,
  lmsProviderCreationDocRef,
  lmsProviderDocRef,
  lmsProvidersCollectionRef,
  lmsRosterMembershipsCollectionRef,
  lmsRosterMembershipDocRef,
  lmsRosterMembershipCreationDocRef,
  lmsRosterMembershipReaffirmDocRef,
  lmsRosterMembershipRemovalDocRef,
  enrollmentCreationDocRef,
  enrollmentDocRef,
  enrollmentStatusChangeDocRef,
  enrollmentsCollectionRef,
  schoolCreationDocRef,
  schoolDocRef,
  submissionCreationDocRef,
  submissionDocRef,
  submissionFinalizationDocRef,
  submissionsCollectionRef,
  teacherPreferencesDocRef,
  teacherPreferencesUpdateDocRef,
  userDocRef,
  userRecordDocRef,
  externalIdentitiesCollectionRef,
  externalIdentityDocRef,
  externalIdentityCreationDocRef,
  externalIdentityRevocationDocRef,
  externalIdentityRestorationDocRef,
  studentAccommodationDocRef,
  studentAccommodationCreationDocRef,
  studentAccommodationUpdateDocRef,
  studentAccommodationHistoryDocRef,
} from "./firestore/typed-ref";
export {
  launchGrantCreationDocRef,
  launchGrantDocRef,
} from "./firestore/typed-ref";
export {
  presentationVariantIndexDocRef,
} from "./firestore/typed-ref";
export {
  PRESENTATION_VARIANTS_COLLECTION,
  presentationVariantIndexDocId,
  isValidPresentationRevisionId,
  isValidVariantKey,
  isValidLessonSlugForVariant,
  variantKeyForReadingLevel,
  assertActivateWriteConsistent,
  type PresentationVariantIndexDoc,
  type PresentationVariantStatus,
} from "./types/presentation-variant";
export {
  LAUNCH_GRANTS_COLLECTION,
  LAUNCH_GRANT_TTL_MS,
  assertLaunchGrantPairInvariant,
  computeGrantExpiryMs,
  isValidGrantId,
  type LaunchGrantCreationWrite,
  type LaunchGrantOutcomeAtIssuance,
  type LaunchGrantRecord,
} from "./types/launch-grant";
export { generateGrantId } from "./presentation/launch-grant-id";
export {
  createLaunchPresentationResolver,
  type LaunchFallbackReason,
  type LaunchPresentation,
  type LaunchPresentationResolution,
  type LaunchPresentationResolver,
  type LaunchPresentationResolverPorts,
  type LaunchPresentationTelemetryEvent,
  type MintGrantInput,
  type ReadingResolution,
  type ResolveLaunchPresentationInput,
  type VariantIndexEvaluation,
} from "./presentation/resolve-launch-presentation";
export {
  buildLaunchPresentationResolverPorts,
  createRequestLaunchPresentationResolver,
} from "./presentation/launch-presentation-deps";
export { runFirestoreTransaction } from "./firestore/transaction";
export { createFirestoreBatch } from "./firestore/batch";
export { log, type LogPayload } from "./logging/logger";
export {
  ASSIGNMENTS_COLLECTION,
  type AssignmentArchiveWrite,
  type AssignmentCloseWrite,
  type AssignmentCreationWrite,
  type AssignmentDraftUpdateWrite,
  type AssignmentLmsPublicationWrite,
  type AssignmentMode,
  type AssignmentPublishWrite,
  type AssignmentReopenWrite,
  type AssignmentRecord,
  type AssignmentStatus,
} from "./types/assignment";
export {
  ASSIGNMENT_RECIPIENTS_SUBCOLLECTION,
  type AssignmentRecipientCreationWrite,
  type AssignmentRecipientRecord,
  type AssignmentRecipientSource,
  type AssignmentRecipientStatus,
} from "./types/assignment-recipient";
export {
  AUDIT_ACTIONS,
  AUDIT_EVENTS_COLLECTION,
  type ActorRole,
  type AuditAction,
  type AuditEventRecord,
  type AuditEventWrite,
  type AuditPayload,
  type AuditTargetType,
} from "./types/audit-event";
export {
  CLASSES_COLLECTION,
  type ActiveClassRecord,
  type ArchivedClassRecord,
  type ClassActivationWrite,
  type ClassArchiveWrite,
  type ClassCreationWrite,
  type ClassLmsCreationWrite,
  type ClassLmsLinkWrite,
  type ClassMetadataUpdateWrite,
  type ClassRecord,
  type ClassStatus,
  type NeedsSetupClassRecord,
} from "./types/class";
export {
  assertClassSupports,
  type ClassOperation,
} from "./classes";
export {
  LMS_ASSIGNMENT_PUBLICATIONS_COLLECTION,
  LMS_CLASS_LINKS_COLLECTION,
  LMS_CONNECTIONS_COLLECTION,
  LMS_PROVIDERS_COLLECTION,
  LMS_ROSTER_MEMBERSHIPS_COLLECTION,
  type ClassEnrollmentSource,
  type LmsAssignmentPublicationCreationWrite,
  type LmsAssignmentPublicationRecord,
  type LmsAssignmentPublicationStatus,
  type LmsClassLinkBreakWrite,
  type LmsClassLinkCreationWrite,
  type LmsClassLinkRecord,
  type LmsClassLinkStatus,
  type LmsClassLinkUnlinkWrite,
  type LmsConnectionCreationWrite,
  type LmsConnectionRecord,
  type LmsConnectionRevocationWrite,
  type LmsConnectionStatus,
  type LmsProviderCreationWrite,
  type LmsProviderId,
  type LmsProviderRecord,
  type LmsRosterMembershipCreationWrite,
  type LmsRosterMembershipReaffirmWrite,
  type LmsRosterMembershipRecord,
  type LmsRosterMembershipRemovalWrite,
  type LmsRosterMembershipStatus,
} from "./types/lms";
export {
  ENROLLMENTS_COLLECTION,
  type EnrollmentCreationWrite,
  type EnrollmentRecord,
  type EnrollmentStatus,
  type EnrollmentStatusChangeWrite,
} from "./types/enrollment";
export {
  SCHOOLS_COLLECTION,
  type SchoolCreationWrite,
  type SchoolRecord,
} from "./types/school";
export {
  SUBMISSIONS_COLLECTION,
  type SubmissionCreationWrite,
  type SubmissionFinalizationWrite,
  type SubmissionRecord,
  type SubmissionResponse,
  type SubmissionStatus,
} from "./types/submission";
export {
  ASSESSMENT_SESSIONS_COLLECTION,
  type AssessmentSessionAutosaveWrite,
  type AssessmentSessionCreationWrite,
  type AssessmentSessionRecord,
  type AssessmentSessionResponse,
  type AssessmentSessionStatus,
  type DeliveryOutcome,
  type SessionDeliveryFreeze,
} from "./types/assessment-session";
export {
  ASSESSMENTS_COLLECTION,
  ASSESSMENT_ANSWER_KEYS_COLLECTION,
  ASSESSMENT_REVISIONS_COLLECTION,
  ASSESSMENT_SCHEMA_VERSION_V1,
  type AssessmentAnswerKeyDeploymentWrite,
  type AssessmentAnswerKeyItem,
  type AssessmentAnswerKeyRecord,
  type AssessmentDeploymentWrite,
  type AssessmentItemOrderingRule,
  type AssessmentItemType,
  type AssessmentRecord,
  type AssessmentRevisionDeploymentWrite,
  type AssessmentRevisionItem,
  type AssessmentRevisionItemOption,
  type AssessmentRevisionRecord,
  type AssessmentSchemaVersion,
} from "./types/assessment";
export {
  ATTEMPTS_COLLECTION,
  type AssessmentAttemptCreationWrite,
  type AssessmentAttemptItemResult,
  type AssessmentAttemptRecord,
} from "./types/attempt";
export {
  EXTERNAL_IDENTITIES_COLLECTION,
  type ExternalIdentityCreationWrite,
  type ExternalIdentityProviderId,
  type ExternalIdentityRecord,
  type ExternalIdentityRestorationWrite,
  type ExternalIdentityRevocationWrite,
  type ExternalIdentitySource,
  type ExternalIdentityStatus,
} from "./types/external-identity";
export {
  assertValidProviderAccountId,
  assertValidProviderId,
  computeExternalIdentityDocId,
  type ExternalIdentityDocIdInput,
} from "./identity/external-identity-doc-id";
export {
  createOrConfirmExternalIdentity,
  listActiveExternalIdentityHashesForUser,
  listExternalIdentitiesForUser,
  reconcileExternalIdentityForUser,
  resolveActiveExternalIdentity,
  resolveActiveUserIdByExternalIdentityDocId,
  restoreExternalIdentity,
  revokeExternalIdentity,
  type CreateOrConfirmInput,
  type CreateOrConfirmOutcome,
  type CreateOrConfirmResult,
  type ExternalIdentityResolution,
  type ReconcileForUserInput,
  type ReconcileForUserPerProviderResult,
  type ReconcileForUserResult,
  type RestoreInput,
  type RestoreOutcome,
  type RestoreResult,
  type RevokeInput,
  type RevokeOutcome,
  type RevokeResult,
} from "./identity/external-identity-store";
export {
  TEACHER_DEFAULT_GRADE_VALUES,
  TEACHER_PREFERENCES_DOC_ID,
  TEACHER_PREFERENCES_SUBCOLLECTION,
  isTeacherDefaultGrade,
  type TeacherDefaultGrade,
  type TeacherPreferencesClearWrite,
  type TeacherPreferencesDoc,
  type TeacherPreferencesSetWrite,
  type TeacherPreferencesUpdateWrite,
} from "./types/teacher-preferences";
export {
  USERS_COLLECTION,
  type ConsentState,
  type Role,
  type StudentActivationWrite,
  type StudentProfile,
  type TeacherApprovalWrite,
  type TeacherDenialWrite,
  type TeacherPilotActivationWrite,
  type TeacherProfile,
  type TeacherVerificationRequestWrite,
  type UserProvisioningWrite,
  type UserRecord,
  type UserStatus,
} from "./types/user";
